"""std0-quant: auditable behavioral reconstruction of Polymarket trader std0.

Phase 1 scope only: reliable, replayable, leak-free data infrastructure.
This project does NOT place real trades and never handles private keys.
"""

__version__ = "0.1.0"

# Frozen research definitions (mirrored from the research spec; do not edit).
EPISODE_RULE_VERSION = "v1_3sec"
EPISODE_WINDOW_SECONDS = 3
Y30_HORIZON_SECONDS = 30

# Exclusion reasons (enum; see README "Exclusion policy").
EXCLUDE_FIELD_INCOMPLETE = "FIELD_INCOMPLETE"
EXCLUDE_SAME_SECOND_AMBIGUITY = "SAME_SECOND_DIRECTION_AMBIGUITY"
EXCLUDE_MARKET_METADATA_MISSING = "MARKET_METADATA_MISSING"
EXCLUDE_INSUFFICIENT_Y30_HORIZON = "INSUFFICIENT_Y30_HORIZON"
EXCLUDE_BOOK_DATA_MISSING = "BOOK_DATA_MISSING"
EXCLUDE_BTC_DATA_MISSING = "BTC_DATA_MISSING"
EXCLUDE_TIMESTAMP_INVALID = "TIMESTAMP_INVALID"
EXCLUDE_OTHER = "OTHER"

EXCLUDE_REASONS = (
    EXCLUDE_FIELD_INCOMPLETE,
    EXCLUDE_SAME_SECOND_AMBIGUITY,
    EXCLUDE_MARKET_METADATA_MISSING,
    EXCLUDE_INSUFFICIENT_Y30_HORIZON,
    EXCLUDE_BOOK_DATA_MISSING,
    EXCLUDE_BTC_DATA_MISSING,
    EXCLUDE_TIMESTAMP_INVALID,
    EXCLUDE_OTHER,
)
